import { publicAsset } from "@/lib/site";

export const categories = [
  "Painted Bottles",
  "Digital Art",
  "Mandalas & Line Art",
  "Rangoli",
  "Canvas Paintings",
  "Resin & Craft",
] as const;

export type Category = (typeof categories)[number];
export type Format = "original" | "print" | "commission";
export type Media = { readonly kind: "image"; readonly src: string; readonly alt: string } | { readonly kind: "video"; readonly src: string; readonly poster: string; readonly alt: string };

export type Artwork = {
  readonly id: string;
  readonly slug: string;
  readonly title: string;
  readonly category: Category;
  readonly description: string;
  readonly tags: readonly string[];
  readonly medium: string | null;
  readonly year: number | null;
  readonly dimensions: string | null;
  readonly price: number | null;
  readonly availability: "available";
  readonly formats: readonly Format[];
  readonly cover: Media;
  readonly media: readonly Media[];
  readonly colors: readonly string[];
  readonly featured: boolean;
};

const image = (name: string, alt: string): Media => ({ kind: "image", src: publicAsset(`/artworks/${name}.jpg`), alt });
const video = (name: string, poster: string, alt: string): Media => ({ kind: "video", src: publicAsset(`/artworks/${name}.webm`), poster: publicAsset(`/artworks/${poster}.jpg`), alt });

export const artworks: readonly Artwork[] = [
  { id: "bottle-ganesha", slug: "ganesha-glow", title: "Ganesha Glow", category: "Painted Bottles", description: "A celebratory hand-painted bottle with a vivid sacred motif and jewel-toned detail.", tags: ["bottle art", "ganesha", "upcycled"], medium: "Hand-painted glass bottle", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("ganesha-glow", "Hand-painted bottle with a colourful Ganesha motif"), media: [image("ganesha-glow", "Hand-painted bottle with a colourful Ganesha motif"), video("bottle-process", "ganesha-glow", "Process video of hand-painted bottle art")], colors: ["#076c52", "#ef4d27", "#e7ab25"], featured: true },
  { id: "bottle-peacock", slug: "peacock-nocturne", title: "Peacock Nocturne", category: "Painted Bottles", description: "A deep blue bottle alive with peacock feathers, dots, and night-garden colour.", tags: ["bottle art", "peacock", "blue"], medium: "Hand-painted glass bottle", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("peacock-nocturne", "Blue hand-painted bottle with peacock artwork"), media: [image("peacock-nocturne", "Blue hand-painted bottle with peacock artwork"), image("starlit-peacock", "Detailed peacock bottle artwork"), image("blue-ganesha", "Blue hand-painted bottle with dotted detail")], colors: ["#082d67", "#0f9a99", "#d8ac31"], featured: true },
  { id: "bottle-crimson", slug: "crimson-folklore", title: "Crimson Folklore", category: "Painted Bottles", description: "A bright red bottle carrying layered characters and a festive folk-art rhythm.", tags: ["bottle art", "folk", "red"], medium: "Hand-painted glass bottle", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("crimson-folklore", "Crimson hand-painted bottle with folk-art details"), media: [image("crimson-folklore", "Crimson hand-painted bottle with folk-art details")], colors: ["#c8292f", "#f68b2c", "#18264e"], featured: false },
  { id: "bottle-rabbit", slug: "festival-rabbit", title: "Festival Rabbit", category: "Painted Bottles", description: "A playful bottle transformed into a whimsical character for joyful spaces and gifting.", tags: ["bottle art", "character", "gift"], medium: "Hand-painted glass bottle", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("festival-rabbit", "Whimsical rabbit-themed painted bottle"), media: [image("festival-rabbit", "Whimsical rabbit-themed painted bottle")], colors: ["#e42d46", "#f5dfb6", "#1e71bf"], featured: false },
  { id: "bottle-words", slug: "words-to-keep", title: "Words to Keep", category: "Painted Bottles", description: "A personalised typography bottle made for messages worth keeping close.", tags: ["bottle art", "typography", "custom"], medium: "Hand-painted glass bottle", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("words-to-keep", "Hand-painted quote bottle"), media: [image("words-to-keep", "Hand-painted quote bottle")], colors: ["#ece1c5", "#8e4736", "#271d24"], featured: false },
  { id: "bottle-owl", slug: "owl-garden", title: "Owl Garden", category: "Painted Bottles", description: "A cheerful owl character surrounded by lush, high-contrast colour.", tags: ["bottle art", "owl", "gift"], medium: "Hand-painted glass bottle", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("owl-garden", "Colourful owl painted on a bottle"), media: [image("owl-garden", "Colourful owl painted on a bottle")], colors: ["#00a5bc", "#eaa41b", "#ed5a45"], featured: false },
  { id: "digital-butterfly", slug: "turquoise-metamorphosis", title: "Turquoise Metamorphosis", category: "Digital Art", description: "A luminous butterfly study hovering between delicacy and electric colour.", tags: ["digital art", "butterfly", "turquoise"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("turquoise-metamorphosis", "Turquoise butterfly digital illustration"), media: [image("turquoise-metamorphosis", "Turquoise butterfly digital illustration")], colors: ["#007d8d", "#0e3142", "#d8ebdb"], featured: true },
  { id: "digital-burj", slug: "burj-after-dark", title: "Burj After Dark", category: "Digital Art", description: "Dubai's skyline reimagined through saturated night colour and a glowing vertical rhythm.", tags: ["digital art", "Dubai", "skyline"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("burj-after-dark", "Digital artwork of Burj Khalifa at night"), media: [image("burj-after-dark", "Digital artwork of Burj Khalifa at night"), image("dubai-after-dark", "Colourful Dubai skyline digital illustration")], colors: ["#15225d", "#545bc0", "#f1a824"], featured: true },
  { id: "digital-betta", slug: "moonlit-betta", title: "Moonlit Betta", category: "Digital Art", description: "A soft, flowing betta fish rendered in cool blue water and bright fins.", tags: ["digital art", "fish", "blue"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("moonlit-betta", "Colourful betta fish digital illustration"), media: [image("moonlit-betta", "Colourful betta fish digital illustration")], colors: ["#10336a", "#66c3da", "#f1a44c"], featured: false },
  { id: "digital-mosque", slug: "violet-minarets", title: "Violet Minarets", category: "Digital Art", description: "An evening architectural portrait glowing with violet light and quiet symmetry.", tags: ["digital art", "mosque", "architecture"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("violet-minarets", "Purple mosque digital illustration at night"), media: [image("violet-minarets", "Purple mosque digital illustration at night")], colors: ["#3f1e6d", "#9f68cb", "#e9be91"], featured: false },
  { id: "digital-rose", slug: "velvet-rose", title: "Velvet Rose", category: "Digital Art", description: "A rich red rose study composed against a theatrical dark ground.", tags: ["digital art", "floral", "rose"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("velvet-rose", "Red rose digital artwork"), media: [image("velvet-rose", "Red rose digital artwork")], colors: ["#821526", "#381719", "#3a7538"], featured: false },
  { id: "digital-eye", slug: "watchful", title: "Watchful", category: "Digital Art", description: "A detailed graphite eye study that holds the viewer's gaze.", tags: ["digital art", "portrait", "graphite"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("watchful", "Detailed monochrome eye artwork"), media: [image("watchful", "Detailed monochrome eye artwork")], colors: ["#171717", "#9b9b9b", "#eeeeee"], featured: false },
  { id: "digital-feather", slug: "electric-feather", title: "Electric Feather", category: "Digital Art", description: "A peacock feather carries its own tiny universe in turquoise and gold.", tags: ["digital art", "feather", "peacock"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("electric-feather", "Peacock feather digital illustration"), media: [image("electric-feather", "Peacock feather digital illustration")], colors: ["#44c3d0", "#c08712", "#09666c"], featured: false },
  { id: "digital-northern", slug: "northern-lights", title: "Northern Lights", category: "Digital Art", description: "A blue-green aurora folds across a silent midnight landscape.", tags: ["digital art", "landscape", "aurora"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("northern-lights", "Northern lights digital landscape"), media: [image("northern-lights", "Northern lights digital landscape")], colors: ["#032f55", "#0a8894", "#95d4cb"], featured: false },
  { id: "mandala-orbit", slug: "quiet-orbit", title: "Quiet Orbit", category: "Mandalas & Line Art", description: "A meditative circular mandala built through patient black-and-white linework.", tags: ["mandala", "line art", "monochrome"], medium: "Ink illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("quiet-orbit", "Monochrome floral mandala"), media: [image("quiet-orbit", "Monochrome floral mandala"), image("midnight-lotus", "Detailed white mandala on black background")], colors: ["#151515", "#d7d7d7", "#ffffff"], featured: true },
  { id: "mandala-sunset", slug: "sunset-promise", title: "Sunset Promise", category: "Mandalas & Line Art", description: "A colourful mandala-framed silhouette scene made for warm, story-filled rooms.", tags: ["mandala", "sunset", "colour"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("sunset-promise", "Colourful sunset mandala illustration with silhouettes"), media: [image("sunset-promise", "Colourful sunset mandala illustration with silhouettes")], colors: ["#f23256", "#f6b021", "#107169"], featured: true },
  { id: "mandala-violet", slug: "violet-geometry", title: "Violet Geometry", category: "Mandalas & Line Art", description: "A crisp radial mandala in violet, blue, and a bright electric centre.", tags: ["mandala", "violet", "geometry"], medium: "Digital illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("violet-geometry", "Violet and blue radial mandala"), media: [image("violet-geometry", "Violet and blue radial mandala"), image("pink-bloom", "Pink and violet floral mandala")], colors: ["#7028bc", "#1b9ad7", "#f257ac"], featured: false },
  { id: "mandala-ganesha", slug: "sacred-ganesha", title: "Sacred Ganesha", category: "Mandalas & Line Art", description: "An intricate devotional portrait created through patterned ink and careful symmetry.", tags: ["mandala", "ganesha", "ink"], medium: "Ink illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("sacred-ganesha", "Detailed Ganesha line art"), media: [image("sacred-ganesha", "Detailed Ganesha line art")], colors: ["#1f1f1f", "#f0eee7", "#77716e"], featured: false },
  { id: "mandala-time", slug: "time-in-bloom", title: "Time in Bloom", category: "Mandalas & Line Art", description: "An hourglass illustration that lets pattern and time spill into one another.", tags: ["mandala", "hourglass", "ink"], medium: "Ink illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("time-in-bloom", "Mandala hourglass line illustration"), media: [image("time-in-bloom", "Mandala hourglass line illustration")], colors: ["#1f1e1c", "#c9bcb5", "#f5f0e8"], featured: false },
  { id: "mandala-teddy", slug: "teddy-halo", title: "Teddy Halo", category: "Mandalas & Line Art", description: "A playful teddy portrait placed inside an ornamental monochrome halo.", tags: ["mandala", "teddy", "line art"], medium: "Ink illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("teddy-halo", "Teddy bear illustration with mandala halo"), media: [image("teddy-halo", "Teddy bear illustration with mandala halo")], colors: ["#1d1d1d", "#aeaeae", "#fafafa"], featured: false },
  { id: "mandala-treat", slug: "midnight-treat", title: "Midnight Treat", category: "Mandalas & Line Art", description: "A sweet, surreal ice-cream illustration filled with miniature pattern work.", tags: ["mandala", "ice cream", "ink"], medium: "Ink illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("midnight-treat", "Ice cream illustration with mandala patterns"), media: [image("midnight-treat", "Ice cream illustration with mandala patterns")], colors: ["#171717", "#f2eee7", "#c5a08f"], featured: false },
  { id: "mandala-crescent", slug: "crescent-prayer", title: "Crescent Prayer", category: "Mandalas & Line Art", description: "A crescent-moon line piece balancing calm detail and gentle symbolism.", tags: ["mandala", "moon", "ink"], medium: "Ink illustration", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("crescent-prayer", "Decorative crescent moon line artwork"), media: [image("crescent-prayer", "Decorative crescent moon line artwork")], colors: ["#121212", "#e9e5dc", "#a38982"], featured: false },
  { id: "rangoli-diya", slug: "diya-bloom", title: "Diya Bloom", category: "Rangoli", description: "A radiant rangoli arranged around a diya, designed to make celebration feel immersive.", tags: ["rangoli", "diya", "event decor"], medium: "Coloured rangoli powder", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("diya-bloom", "Colourful rangoli with diya lamp"), media: [image("diya-bloom", "Colourful rangoli with diya lamp")], colors: ["#ec3f71", "#f9cb25", "#6751cc"], featured: true },
  { id: "rangoli-garden", slug: "festival-garden", title: "Festival Garden", category: "Rangoli", description: "A bold floral rangoli with saturated greens, oranges, and blue petals.", tags: ["rangoli", "floral", "event decor"], medium: "Coloured rangoli powder", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("festival-garden", "Large colourful floral rangoli"), media: [image("festival-garden", "Large colourful floral rangoli")], colors: ["#51bc37", "#ed4331", "#244baa"], featured: false },
  { id: "rangoli-circle", slug: "circle-of-celebration", title: "Circle of Celebration", category: "Rangoli", description: "A bright circular rangoli composed for festive floors, entrances, and gatherings.", tags: ["rangoli", "festival", "commission"], medium: "Coloured rangoli powder", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("circle-of-celebration", "Colourful circular rangoli with lamps"), media: [image("circle-of-celebration", "Colourful circular rangoli with lamps")], colors: ["#f18e21", "#e72d54", "#2770b8"], featured: false },
  { id: "rangoli-peacock", slug: "peacock-petals", title: "Peacock Petals", category: "Rangoli", description: "A blue-petalled rangoli whose centre blooms in peacock-inspired colour.", tags: ["rangoli", "peacock", "commission"], medium: "Coloured rangoli powder", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("peacock-petals", "Blue peacock-inspired rangoli"), media: [image("peacock-petals", "Blue peacock-inspired rangoli")], colors: ["#123f9d", "#f4a32e", "#4bbd7c"], featured: false },
  { id: "canvas-wings", slug: "wings-in-gold", title: "Wings in Gold", category: "Canvas Paintings", description: "A sunlit butterfly diptych that brings blue, gold, and movement into an interior.", tags: ["canvas", "butterfly", "diptych"], medium: "Acrylic on canvas", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("wings-in-gold", "Yellow butterfly canvas diptych in an interior"), media: [image("wings-in-gold", "Yellow butterfly canvas diptych in an interior")], colors: ["#1c6394", "#edba2c", "#d9e6eb"], featured: true },
  { id: "canvas-dreams", slug: "into-her-dreams", title: "Into Her Dreams", category: "Canvas Paintings", description: "A fearless pink typographic canvas for a room that needs a little more conviction.", tags: ["canvas", "typography", "pink"], medium: "Acrylic on canvas", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("into-her-dreams", "Pink motivational typography canvas"), media: [image("into-her-dreams", "Pink motivational typography canvas")], colors: ["#e73979", "#f995c4", "#251022"], featured: false },
  { id: "canvas-radha", slug: "radha-krishna-reverie", title: "Radha Krishna Reverie", category: "Canvas Paintings", description: "A vivid devotional canvas built from tender colour, ornament, and story.", tags: ["canvas", "Radha Krishna", "devotional"], medium: "Acrylic on canvas", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("radha-krishna-reverie", "Colourful Radha Krishna canvas painting"), media: [image("radha-krishna-reverie", "Colourful Radha Krishna canvas painting")], colors: ["#f3c22d", "#117297", "#f08a4b"], featured: false },
  { id: "canvas-folk", slug: "folk-wedding", title: "Folk Wedding", category: "Canvas Paintings", description: "A richly patterned folk-art narrative celebrating companionship and ceremony.", tags: ["canvas", "folk art", "narrative"], medium: "Acrylic on canvas", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("folk-wedding", "Colourful folk-art canvas painting"), media: [image("folk-wedding", "Colourful folk-art canvas painting")], colors: ["#da4637", "#f0c830", "#24716c"], featured: false },
  { id: "canvas-moon", slug: "moonlit-stillness", title: "Moonlit Stillness", category: "Canvas Paintings", description: "A winter-night landscape where a full moon turns the quiet blue.", tags: ["canvas", "landscape", "moon"], medium: "Acrylic on canvas", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("moonlit-stillness", "Moonlit winter landscape canvas painting"), media: [image("moonlit-stillness", "Moonlit winter landscape canvas painting")], colors: ["#47699e", "#edf2e8", "#1b2d51"], featured: false },
  { id: "canvas-tidal", slug: "tidal-blue", title: "Tidal Blue", category: "Canvas Paintings", description: "A fluid blue canvas study, alive with the movement of poured paint.", tags: ["canvas", "fluid art", "blue"], medium: "Fluid acrylic on canvas", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("tidal-blue", "Blue fluid acrylic canvas painting"), media: [image("tidal-blue", "Blue fluid acrylic canvas painting"), video("tidal-blue-process", "tidal-blue", "Fluid canvas painting process video")], colors: ["#024d83", "#0a9fba", "#d7e9e7"], featured: false },
  { id: "canvas-feather", slug: "peacock-feather-studies", title: "Peacock Feather Studies", category: "Canvas Paintings", description: "A textural peacock-feather composition made to add a little ceremony to a wall.", tags: ["canvas", "peacock", "texture"], medium: "Acrylic on canvas", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("peacock-feather-studies", "Peacock feather canvas painting"), media: [image("peacock-feather-studies", "Peacock feather canvas painting")], colors: ["#16659d", "#cda22f", "#efe2b5"], featured: false },
  { id: "craft-ganesha", slug: "ganesha-craft", title: "Ganesha Craft", category: "Resin & Craft", description: "A handmade devotional craft piece created with intricate surface pattern and character.", tags: ["craft", "Ganesha", "handmade"], medium: "Handcrafted mixed media", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("blue-ganesha", "Handmade Ganesha craft artwork"), media: [image("blue-ganesha", "Handmade Ganesha craft artwork")], colors: ["#171717", "#f4eee5", "#a95456"], featured: false },
  { id: "resin-rose", slug: "rose-quartz-coasters", title: "Rose Quartz Coasters", category: "Resin & Craft", description: "A set of translucent pink resin coasters with soft gold edges and floral warmth.", tags: ["resin", "coasters", "gift"], medium: "Resin", year: null, dimensions: null, price: null, availability: "available", formats: ["original", "print", "commission"], cover: image("rose-quartz-coasters", "Pink resin coasters with gold edges"), media: [image("rose-quartz-coasters", "Pink resin coasters with gold edges")], colors: ["#d683a1", "#eee1c5", "#a87332"], featured: true },
];

export const getArtwork = (slug: string): Artwork | undefined => artworks.find((artwork) => artwork.slug === slug);
export const getRelated = (artwork: Artwork): readonly Artwork[] => artworks.filter((item) => item.category === artwork.category && item.id !== artwork.id).slice(0, 3);
